targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          - lib/main/main_local.dart
          - lib/main/main_prod.dart
      reflectable:
        generate_for:
          - no/files
      flutter_localizations:
        generate_for:
          - lib/l10n/*.arb
