name: flutter_bloc_advance
description: "Flutter Bloc Advance Template"
publish_to: 'none'
version: 0.13.1+1

environment:
  sdk: ^3.8.1
  flutter: '3.32.8'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 8.1.6
  go_router: 16.1.0
  equatable: 2.0.7
  intl: 0.20.2
  dart_json_mapper: 2.2.16
  flutter_form_builder: 10.1.0
  form_builder_validators: 11.2.0
  reflectable: 4.0.13
  shared_preferences: 2.5.3
  logger: 2.6.1
  get_storage: 2.1.1
  http: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  integration_test:
    sdk: flutter
  build_runner: 2.4.15
  test: 1.25.15
  bloc_test: 9.1.7
  mockito: ^5.4.5
  analyzer: ^6.11.0
  flutter_launcher_icons: ^0.14.2

flutter_secure_storage:
  enabled: true
  class_name: SecureStorage
  main_locale: en

flutter_intl:
  enabled: true
  template-arb-file: lib/l10n/intl_en.arb
  output-localization-file: l10n.dart
  output-class: S

flutter:
  uses-material-design: true
  generate: true
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
  assets:
    - assets/mock/
    - assets/images/
    - assets/lidya_logo_animation.gif
    - assets/lidya_sampled_frames_landing_animation_background/
    - assets/lidya-genomics-logo/

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/lidya-genomics-logo/02-web-mobil/app-icon/lidya-genomics-appicon-02/apple/apple-icon-60x60.png
  remove_alpha_ios: true